### ISSUE TITLE
I'm not able to get the Lync Archiver Utility program to work.

### ISSUE THREAD

**Issue by PlayThatMusic** [avsnarayan/LyncArchiverUtil#12]
Hello,

I downloaded and installed version 1.0.0.3.  I did not receive any error messages during the install.  I am using the 32-bit version of Windows 7.

I can see the Icon in the system tray.  It says "Lync Archiver Utility" when I mouse over it, but nothing happens (no menu and the program does not come up)  when I Left-click or Right-click (single or double click) on that icon in the system tray.

I tried setting it to "Run this program as administrator" and "Windows XP (service pack 3)", but it did not help.

Any help you could provide me to get it working on my computer, that would be Great!

Thanks,
David.

**Comment by avsnarayan** [comment]
Tray icon is action-less. You can see your conversations in C:\Conversations folder.
All conversations after installation are logged here. If you do not see the files. Let me know.
