### ISSUE TITLE
can't log the conversation after drag someone into existing windows

### ISSUE THREAD

**Issue by billmoling** [avsnarayan/LyncArchiverUtil#13]
Like A is chatting with B. if A drag C into this existing conversation, it between a group with A,B and C, and this window won't be logged in the archiver.

**Comment by bujocek** [comment]
Good point. Thanks for this issue. 
You are a programmer - do you have some time to fix it? Because I am quite busy now and don't know when I will fix it myself. I could assign the issue to you and grant you access to the project if you are up to it.

**Comment by avsnarayan** [comment]
This should work. File name would be B_C.conv or the order by which users are added.
