### ISSUE TITLE
uncorrect append on conv file 

### ISSUE THREAD

**Issue by twproject** [avsnarayan/LyncArchiverUtil#17]
I start a chat with a collegues yesterday and it create a conv file
today i start a new chat with him again and it attach to the same conv file but it append the new chat in an uncorrect way.

I attach the conv file
[L_C.conv.txt](https://github.com/avsnarayan/LyncArchiverUtil/files/701356/L_C.conv.txt)

**Comment by avsnarayan** [comment]
This is not really possible as code is always trying to write header in a new line.
streamWriter.WriteLine(
                        "--------------------------------------------------------------------------------");
                    streamWriter.WriteLine(DateTime.Now.ToString(CultureInfo.InvariantCulture));
                    streamWriter.WriteLine(
                        "--------------------------------------------------------------------------------");

I could not reproduce it.

**Comment by twproject** [comment]
I retry with latest version but problem happen when day change and the tool append the new data header
[P_S.conv.txt](https://github.com/avsnarayan/LyncArchiverUtil/files/716637/P_S.conv.txt)
i upload another example
